version: '2.3'
services:
    flower:
        image: choonkiatlee/colourize:release
        container_name: flower
        runtime: nvidia
        # depends_on:
        #     - celery_worker
        environment:
            - AZURE_STORAGE_CONNECTION_STRING
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
            - ENABLE_GPU=True
        entrypoint: ["celery", "flower", "-A", "tasks", "--address=0.0.0.0", --broker", "redis://redis:6379/0", "--basic_auth=finderr:Finderr2019"]
        networks:
            api_my-network:
                aliases:
                    - flower
        ports:
            - 5555:5555

networks:
  api_my-network:
    external: true